import React from "react";

const states = [
  { state: "Abia", capital: "Umuahia", slogan: "God’s Own State" },
  { state: "Adamawa", capital: "Yola", slogan: "Land of Beauty" },
  { state: "Akwa Ibom", capital: "Uyo", slogan: "Land of Promise" },
  { state: "Anambra", capital: "Awka", slogan: "Light of the Nation" },
  { state: "Bauchi", capital: "Bauchi", slogan: "Pearl of Tourism" },
  { state: "Bayelsa", capital: "Yenagoa", slogan: "Glory of All Lands" },
  { state: "Benue", capital: "Makurdi", slogan: "Food Basket of the Nation" },
  { state: "Borno", capital: "Maiduguri", slogan: "Home of Peace" },
  { state: "Cross River", capital: "Calabar", slogan: "The People's Paradise" },
  { state: "Delta", capital: "Asaba", slogan: "The Big Heart" },
  { state: "Ebonyi", capital: "Abakaliki", slogan: "Salt of the Nation" },
  { state: "Edo", capital: "Benin City", slogan: "Heartbeat of the Nation" },
  { state: "Ekiti", capital: "Ado-Ekiti", slogan: "Land of Honour and Integrity" },
  { state: "Enugu", capital: "Enugu", slogan: "Coal City State" },
  { state: "Gombe", capital: "Gombe", slogan: "Jewel in the Savannah" },
  { state: "Imo", capital: "Owerri", slogan: "Eastern Heartland" },
  { state: "Jigawa", capital: "Dutse", slogan: "The New World" },
  { state: "Kaduna", capital: "Kaduna", slogan: "Centre of Learning" },
  { state: "Kano", capital: "Kano", slogan: "Centre of Commerce" },
  { state: "Katsina", capital: "Katsina", slogan: "Home of Hospitality" },
  { state: "Kebbi", capital: "Birnin Kebbi", slogan: "Land of Equity" },
  { state: "Kogi", capital: "Lokoja", slogan: "Confluence State" },
  { state: "Kwara", capital: "Ilorin", slogan: "State of Harmony" },
  { state: "Lagos", capital: "Ikeja", slogan: "Centre of Excellence" },
  { state: "Nasarawa", capital: "Lafia", slogan: "Home of Solid Minerals" },
  { state: "Niger", capital: "Minna", slogan: "The Power State" },
  { state: "Ogun", capital: "Abeokuta", slogan: "Gateway State" },
  { state: "Ondo", capital: "Akure", slogan: "Sunshine State" },
  { state: "Osun", capital: "Oshogbo", slogan: "Land of Virtue" },
  { state: "Oyo", capital: "Ibadan", slogan: "Pace Setter State" },
  { state: "Plateau", capital: "Jos", slogan: "Home of Peace and Tourism" },
  { state: "Rivers", capital: "Port Harcourt", slogan: "Treasure Base of the Nation" },
  { state: "Sokoto", capital: "Sokoto", slogan: "Seat of the Caliphate" },
  { state: "Taraba", capital: "Jalingo", slogan: "Nature's Gift to the Nation" },
  { state: "Yobe", capital: "Damaturu", slogan: "Pride of the Sahel" },
  { state: "Zamfara", capital: "Gusau", slogan: "Farming is Our Pride" },
  { state: "FCT", capital: "Abuja", slogan: "Centre of Unity" },
];

export default states;
